services:
  zsequencer:
    container_name: zsequencer-node
    image: zellular/zsequencer:latest
    ports:
      - "6001:6001"
    volumes:
      - "./node/bls_key.json:/app/bls_key.json"
      - "./node/ecdsa_key.json:/app/ecdsa_key.json"
      - db:/db
      - "./node/apps.json:/app/apps.json"
      - "./node/nodes.json:/app/nodes.json"
    environment:
      - ZSEQUENCER_BLS_KEY_FILE=/app/bls_key.json
      - ZSEQUENCER_ECDSA_KEY_FILE=/app/ecdsa_key.json
      - ZSEQUENCER_SNAPSHOT_PATH=/db
      - ZSEQUENCER_APPS_FILE=/app/apps.json
      - ZSEQUENCER_NODES_FILE=/app/nodes.json
    env_file:
      - node/.env

volumes:
  db:
